name: ESLint Security Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm install
    - name: Install ESLint and Plugins
      run: npm install eslint eslint-plugin-security @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
    - name: Run ESLint
      run: npx eslint . --ext .ts,.js --format json --output-file eslint_report.json
    - name: Upload ESLint Report
      uses: actions/upload-artifact@v3
      with:
        name: eslint-report
        path: eslint_report.json